apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app.name }}-master
spec:
  serviceName: {{ .Values.app.name }}-master
  replicas: 1  # Один мастер
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-postgres
      role: master
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-postgres
        role: master
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.master.image }}:{{ .Values.postgres.master.imageVersion }}"
        ports:
          - containerPort: {{ .Values.postgres.port }}
        env:
          - name: POSTGRES_DB
            value: {{ .Values.postgres.db }}
          #- name: POSTGRES_DB
          #  value: {{ .Values.postgres.db }}   
          - name: POSTGRES_PASSWORD
            value: {{ .Values.users.db.password }} 
          - name: POSTGRES_USER
            value: {{ .Values.users.db.username }} 
        volumeMounts:

          - name: {{ .Values.app.name }}-storage
            mountPath: /var/lib/postgresql/data # is standard
            # mountPath: /bitnami/postgresql/data

          #- name: {{ .Values.app.name }}-master-config-volume
          #  mountPath: /etc/postgresql/postgresql.conf # standart for postge images but not for bitnami
            # mountPath: /opt/bitnami/postgresql/conf/postgresql.conf
          #  subPath: postgresql.conf
          #  readOnly: true
          - name: {{ .Values.app.name }}-master-config-volume
            mountPath: /etc/postgresql/pg_hba.conf
            # mountPath: /opt/bitnami/postgresql/conf/pg_hba.conf
            subPath: pg_hba.conf
            readOnly: true
            # and now to /var/lib/postgresql/data
          #- name: {{ .Values.app.name }}-master-config-volume
          #  mountPath: /var/lib/postgresql/data/postgresql.conf # standart for postge images but not for bitnami
            # mountPath: /opt/bitnami/postgresql/conf/postgresql.conf
          #  subPath: postgresql.conf
          #  readOnly: true
          #- name: {{ .Values.app.name }}-master-config-volume
          #  mountPath: /var/lib/postgresql/data/pg_hba.conf
            # mountPath: /opt/bitnami/postgresql/conf/pg_hba.conf
          #  subPath: pg_hba.conf
          #  readOnly: true

        #lifecycle:
        #  postStart:
        #    exec:
              #command: ["/bin/sh", "-c", "cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf && cp /etc/postgresql/postgresql.conf /var/lib/postgresql/data/postgresql.conf"] 
              #command: ["/bin/sh", "-c", "cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf && pg_ctl reload"]
      volumes:
        - name: {{ .Values.app.name }}-master-config-volume
          configMap:
            name: {{ .Values.app.name }}-master-config

  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.app.name }}-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.pvc.resources.requests.storage | quote }}