app:
    name: ecommerce
    ingressDomain: dev.saas.tdm.com
    frontend: null
    backend:
        apiGateway:
            name: ecommerce-api-gateway
            replicas: 1
            labels:
                components: ecommerce-api-gateway
            image: ecommerce-api-gateway
            imageVersion: v1.dev.029
            port: 3999
            resources:
                limits:
                    memory: 2000Mi
                    cpu: 500m
            env:
                - RUN_MODE
                - ENV
                - DSN
                - LIQUIBASE_MIGRATION
                - SHARDS_URL
                - SHARDS_TOKEN
                - ID_CREATOR_NODE
                - OAUTH2_STATE_TOKEN_SECRET
                - OAUTH2_STATE_TOKEN_EXPIRATION
                - GOOGLE_CLIENT_ID
                - JWT_SECRET
                - JWT_ACCESS_TOKEN_EXPIRATION
                - JWT_REFRESH_TOKEN_EXPIRATION
                - JWT_OTP_SECRET
                - JWT_OTP_VERIFICATION_TOKEN_EXPIRATION
                - JWT_OTP_ISSUER
                - OTP_SMS_SERVICE_URL
                - OTP_EMAIL_SERVICE_URL
                - OTP_EMAIL_SERVICE_TOKEN
                - OTP_EXPIRATION
                - OTP_LENGTH
                - JWT_USER_ACCESS_TOKEN_EXPIRATION
                - JWT_USER_REFRESH_TOKEN_EXPIRATION
                - JWT_CUSTOMER_SECRET
                - JWT_CUSTOMER_ACCESS_TOKEN_EXPIRATION
                - JWT_CUSTOMER_REFRESH_TOKEN_EXPIRATION
                - JWT_CUSTOMER_CSRF_TOKEN_LENGTH
                #PARTNER
                - JWT_PARTNER_ACCESS_TOKEN_EXPIRATION
                ###################################################
                #REDIS & CACHE
                - REDIS_URL
                #REDIS_PORT=6380
                - REDIS_PORT
                - REDIS_PASSWORD
                - REDIS_TTL
                - L1TTL
                - L1CLEANUP_INTERVAL
                - L2TTL
                - L2CLEANUP_INTERVAL
                ###################################################
                #TYPESENSE
                - TYPESENSE_URL
                - TYPESENSE_PORT
                - TYPESENSE_APIKEY
                ###################################################
                - LOKI_URL
                - LOKI_PORT
                - LOKI_APIKEY
                ###################################################
                - KAFKA_BROKERS
                #Unique for each pod (
                - KAFKA_PRODUCER_REPLY_TOPIC
                - KAFKA_TX_SERVICEMESSAGES_TOPIC
                - KAFKA_GROUP_ID
                - KAFKA_PRODUCER_QUEUE_SIZE
                - KAFKA_SECURITY_PROTOCOL
                - KAFKA_SASL_MECHANISM
                - KAFKA_SASL_USERNAME
                - KAFKA_SASL_PASSWORD
                - RABBITMQ_URL
                - RABBITMQ_PORT
                - RABBITMQ_USER
                - RABBITMQ_PASSWORD
                ###################################################
                - HH_URL
                - HH_TOKEN
                - GOOGLE_SHEETS
                - GOOGLE_SERVICE_ACCOUNT_JSON_PATH
                #SECRETSSERVICE
                - SECRETS_SERVICE_DSN
                - APP_ID
                - APP_REDIRECT_URI
                #TXCOORDINATOR
                - TXSCOORDINATOR_TX_MAX_LIFETIME
                - CONSUL_APP_ID
                - CONSUL_APP_PATH
                - CONSUL_APP_PORT
                - CONSUL_PATH
                - GRPC_PORT
