apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-pgpool-service
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.app.name }}-pgpool
  type: ClusterIP