apiVersion: v1
kind: Service
metadata:
  #name: {{ .Values.app.name }}-pgpool switch to it later
  name: {{ .Values.app.name }}-pgpool
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }} # added later
  selector:
    app: {{ .Values.app.name }}-pgpool
  type: ClusterIP