apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: saas-v1-external-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-demo-store
    kind: SecretStore
  target:
    name: kafka-sasl-creds    # Имя k8s Secret, который создастся
    creationPolicy: Owner
  data:
    - secretKey: KAFKA_SASL_PASSWORD
      remoteRef:
        key: secret/demo       # путь до секрета в Vault ("demo"),
        property: password     # имя поля в kv ("password")