apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-demo-store
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "secret"         # Mount-путь, чаще всего "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-root-token
          key: token