apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.backend.apiGateway.name }}-secret
type: Opaque
data:
  GOOGLE_SERVICE_ACCOUNT_JSON: {{ .Values.env.GOOGLE_SERVICE_ACCOUNT_JSON | b64enc | quote }}
  DSN: {{ .Values.env.DSN }}
  LIQUIBASE_MIGRATION: {{ .Values.env.LIQUIBASE_MIGRATION | toString | b64enc }}
  SHARDS_URL: {{ .Values.env.SHARDS_URL  | b64enc }}
  SHARDS_TOKEN: {{ .Values.env.SHARDS_TOKEN  | b64enc }}
  ID_CREATOR_NODE: {{ .Values.env.ID_CREATOR_NODE | toString | b64enc }}
  ###################################################
  #OAUTH2
  OAUTH2_STATE_TOKEN_SECRET: {{ .Values.env.OAUTH2_STATE_TOKEN_SECRET | b64enc }}
  OAUTH2_STATE_TOKEN_EXPIRATION: {{ .Values.env.OAUTH2_STATE_TOKEN_EXPIRATION | b64enc }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | b64enc }}
  #AUTH
  #Local strategy
  JWT_SECRET: {{ .Values.env.JWT_SECRET | b64enc }}
  JWT_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_ACCESS_TOKEN_EXPIRATION | b64enc }}
  JWT_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_REFRESH_TOKEN_EXPIRATION | b64enc }}
  #Common jwt startegy
  #OTP
  JWT_OTP_SECRET: {{ .Values.env.JWT_OTP_SECRET | b64enc }}
  JWT_OTP_VERIFICATION_TOKEN_EXPIRATION: {{ .Values.env.JWT_OTP_VERIFICATION_TOKEN_EXPIRATION | b64enc }}
  JWT_OTP_ISSUER: {{ .Values.env.JWT_OTP_ISSUER | toString | b64enc }}
  OTP_SMS_SERVICE_URL: {{ .Values.env.OTP_SMS_SERVICE_URL | b64enc }}
  OTP_EMAIL_SERVICE_URL: {{ .Values.env.OTP_EMAIL_SERVICE_URL | b64enc }}
  OTP_EMAIL_SERVICE_TOKEN: {{ .Values.env.OTP_EMAIL_SERVICE_TOKEN | b64enc }}
  OTP_EXPIRATION: {{ .Values.env.OTP_EXPIRATION | b64enc }}
  OTP_LENGTH: {{ .Values.env.OTP_LENGTH | toString | b64enc }}
  #USER
  JWT_USER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_USER_ACCESS_TOKEN_EXPIRATION | b64enc }}
  JWT_USER_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_USER_REFRESH_TOKEN_EXPIRATION | b64enc }}
  #CUSTOMER
  JWT_CUSTOMER_SECRET: {{ .Values.env.JWT_CUSTOMER_SECRET | b64enc }}
  JWT_CUSTOMER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_CUSTOMER_ACCESS_TOKEN_EXPIRATION | b64enc }}
  JWT_CUSTOMER_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_CUSTOMER_REFRESH_TOKEN_EXPIRATION | b64enc }}
  JWT_CUSTOMER_CSRF_TOKEN_LENGTH: {{ .Values.env.JWT_CUSTOMER_CSRF_TOKEN_LENGTH | toString | b64enc }}
  #PARTNER
  JWT_PARTNER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_PARTNER_ACCESS_TOKEN_EXPIRATION | b64enc }}
  ###################################################
  #REDIS & CACHE
  REDIS_URL: {{ .Values.env.REDIS_URL | b64enc }}
  REDIS_PORT: {{ .Values.env.REDIS_PORT | toString | b64enc }}
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD | b64enc }}
  REDIS_TTL: {{ .Values.env.REDIS_TTL | toString | b64enc }}
  L1TTL: {{ .Values.env.L1TTL | toString | b64enc }}
  L1CLEANUP_INTERVAL: {{ .Values.env.L1CLEANUP_INTERVAL | toString | b64enc}}
  L2TTL: {{ .Values.env.L2TTL | toString | b64enc }}
  L2CLEANUP_INTERVAL: {{ .Values.env.L2CLEANUP_INTERVAL | toString | b64enc }}
  ###################################################
  #TYPESENSE
  TYPESENSE_URL: {{ .Values.env.TYPESENSE_URL | b64enc }}
  TYPESENSE_PORT: {{ .Values.env.TYPESENSE_PORT | toString | b64enc }}
  TYPESENSE_APIKEY: {{ .Values.env.TYPESENSE_APIKEY | b64enc }}
  ###################################################
  LOKI_URL: {{ .Values.env.LOKI_URL | b64enc }}
  LOKI_PORT: {{ .Values.env.LOKI_PORT | toString | b64enc }}
  LOKI_APIKEY: {{ .Values.env.LOKI_APIKEY | toString | b64enc }}
  ###################################################
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS | b64enc }}
  #Unique for each pod (
  KAFKA_PRODUCER_REPLY_TOPIC: {{ .Values.env.KAFKA_PRODUCER_REPLY_TOPIC | b64enc }}
  KAFKA_TX_SERVICEMESSAGES_TOPIC: {{ .Values.env.KAFKA_TX_SERVICEMESSAGES_TOPIC | b64enc }}
  # )
  KAFKA_GROUP_ID: {{ .Values.env.KAFKA_GROUP_ID | toString | b64enc }}
  KAFKA_PRODUCER_QUEUE_SIZE: {{ .Values.env.KAFKA_PRODUCER_QUEUE_SIZE | toString | b64enc }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL | b64enc }}
  RABBITMQ_PORT: {{ .Values.env.RABBITMQ_PORT | toString | b64enc }}
  RABBITMQ_USER: {{ .Values.env.RABBITMQ_USER | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.env.RABBITMQ_PASSWORD | b64enc }}
  ###################################################
  HH_URL: {{ .Values.env.HH_URL | b64enc }}
  HH_TOKEN: {{ .Values.env.HH_TOKEN | b64enc }}
  GOOGLE_SHEETS: {{ .Values.env.GOOGLE_SHEETS | b64enc }}
  GOOGLE_SERVICE_KEY_PATH: {{ .Values.env.GOOGLE_SERVICE_KEY_PATH | b64enc }}
  #SECRETSSERVICE
  SECRETS_SERVICE_DSN: {{ .Values.env.SECRETS_SERVICE_DSN | b64enc }}
  APP_ID: {{ .Values.env.APP_ID | toString | b64enc }}
  APP_REDIRECT_URI: {{ .Values.env.APP_REDIRECT_URI | b64enc }}
  #TXCOORDINATOR
  TXSCOORDINATOR_TX_MAX_LIFETIME: {{ .Values.env.TXSCOORDINATOR_TX_MAX_LIFETIME | b64enc }}