apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.backend.apiGateway.name }}-secret
type: Opaque
data:
  GOOGLE_SERVICE_ACCOUNT_JSON: {{ .Values.env.GOOGLE_SERVICE_ACCOUNT_JSON | b64enc | quote }}
  DSN: {{ .Values.env.DSN }}
  LIQUIBASE_MIGRATION: {{ .Values.env.LIQUIBASE_MIGRATION }}
  SHARDS_URL: {{ .Values.env.SHARDS_URL }}
  SHARDS_TOKEN: {{ .Values.env.SHARDS_TOKEN }}
  ID_CREATOR_NODE: {{ .Values.env.ID_CREATOR_NODE }}
  ###################################################
  #OAUTH2
  OAUTH2_STATE_TOKEN_SECRET: {{ .Values.env.OAUTH2_STATE_TOKEN_SECRET }}
  OAUTH2_STATE_TOKEN_EXPIRATION: {{ .Values.env.OAUTH2_STATE_TOKEN_EXPIRATION }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET }}
  #AUTH
  #Local strategy
  JWT_SECRET: {{ .Values.env.JWT_SECRET }}
  JWT_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_ACCESS_TOKEN_EXPIRATION }}
  JWT_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_REFRESH_TOKEN_EXPIRATION }}
  #Common jwt startegy
  #OTP
  JWT_OTP_SECRET: {{ .Values.env.JWT_OTP_SECRET }}
  JWT_OTP_VERIFICATION_TOKEN_EXPIRATION: {{ .Values.env.JWT_OTP_VERIFICATION_TOKEN_EXPIRATION }}
  JWT_OTP_ISSUER: {{ .Values.env.JWT_OTP_ISSUER }}
  OTP_SMS_SERVICE_URL: {{ .Values.env.OTP_SMS_SERVICE_URL }}
  OTP_EMAIL_SERVICE_URL: {{ .Values.env.OTP_EMAIL_SERVICE_URL }}
  OTP_EMAIL_SERVICE_TOKEN: {{ .Values.env.OTP_EMAIL_SERVICE_TOKEN }}
  OTP_EXPIRATION: {{ .Values.env.OTP_EXPIRATION }}
  OTP_LENGTH: {{ .Values.env.OTP_LENGTH }}
  #USER
  JWT_USER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_USER_ACCESS_TOKEN_EXPIRATION }}
  JWT_USER_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_USER_REFRESH_TOKEN_EXPIRATION }}
  #CUSTOMER
  JWT_CUSTOMER_SECRET: {{ .Values.env.JWT_CUSTOMER_SECRET }}
  JWT_CUSTOMER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_CUSTOMER_ACCESS_TOKEN_EXPIRATION }}
  JWT_CUSTOMER_REFRESH_TOKEN_EXPIRATION: {{ .Values.env.JWT_CUSTOMER_REFRESH_TOKEN_EXPIRATION }}
  JWT_CUSTOMER_CSRF_TOKEN_LENGTH: {{ .Values.env.JWT_CUSTOMER_CSRF_TOKEN_LENGTH }}
  #PARTNER
  JWT_PARTNER_ACCESS_TOKEN_EXPIRATION: {{ .Values.env.JWT_PARTNER_ACCESS_TOKEN_EXPIRATION }}
  ###################################################
  #REDIS & CACHE
  REDIS_URL: {{ .Values.env.REDIS_URL }}
  #REDIS_PORT=6380
  REDIS_PORT: {{ .Values.env.REDIS_PORT }}
  REDIS_PASSWORD: {{ .Values.env.REDIS_PASSWORD }}
  REDIS_TTL: {{ .Values.env.REDIS_TTL }}
  L1TTL: {{ .Values.env.L1TTL }}
  L1CLEANUP_INTERVAL: {{ .Values.env.L1CLEANUP_INTERVAL }}
  L2TTL: {{ .Values.env.L2TTL }}
  L2CLEANUP_INTERVAL: {{ .Values.env.L2CLEANUP_INTERVAL }}
  ###################################################
  #TYPESENSE
  TYPESENSE_URL: {{ .Values.env.TYPESENSE_URL }}
  TYPESENSE_PORT: {{ .Values.env.TYPESENSE_PORT }}
  TYPESENSE_APIKEY: {{ .Values.env.TYPESENSE_APIKEY }}
  ###################################################
  LOKI_URL: {{ .Values.env.LOKI_URL }}
  LOKI_PORT: {{ .Values.env.LOKI_PORT }}
  LOKI_APIKEY: {{ .Values.env.LOKI_APIKEY }}
  ###################################################
  KAFKA_BROKERS: {{ .Values.env.KAFKA_BROKERS }}
  #Unique for each pod (
  KAFKA_PRODUCER_REPLY_TOPIC: {{ .Values.env.KAFKA_PRODUCER_REPLY_TOPIC }}
  KAFKA_TX_SERVICEMESSAGES_TOPIC: {{ .Values.env.KAFKA_TX_SERVICEMESSAGES_TOPIC }}
  # )
  KAFKA_GROUP_ID: {{ .Values.env.KAFKA_GROUP_ID }}
  KAFKA_PRODUCER_QUEUE_SIZE: {{ .Values.env.KAFKA_PRODUCER_QUEUE_SIZE }}
  RABBITMQ_URL: {{ .Values.env.RABBITMQ_URL }}
  RABBITMQ_PORT: {{ .Values.env.RABBITMQ_PORT }}
  RABBITMQ_USER: {{ .Values.env.RABBITMQ_USER }}
  RABBITMQ_PASSWORD: {{ .Values.env.RABBITMQ_PASSWORD }}
  ###################################################
  HH_URL: {{ .Values.env.HH_URL }}
  HH_TOKEN: {{ .Values.env.HH_TOKEN }}
  GOOGLE_SHEETS: {{ .Values.env.GOOGLE_SHEETS }}
  #GOOGLE_SERVICE_KEY_PATH=configs/google-service-account.json
  #GOOGLE_SERVICE_KEY_PATH=../../../configs/google-service-account.json
  GOOGLE_SERVICE_KEY_PATH: {{ .Values.env.GOOGLE_SERVICE_KEY_PATH }}
  #SECRETSSERVICE
  SECRETS_SERVICE_DSN: {{ .Values.env.SECRETS_SERVICE_DSN }}
  APP_ID: {{ .Values.env.APP_ID }}
  APP_REDIRECT_URI: {{ .Values.env.APP_REDIRECT_URI }}
  #TXCOORDINATOR
  TXSCOORDINATOR_TX_MAX_LIFETIME: {{ .Values.env.TXSCOORDINATOR_TX_MAX_LIFETIME }}