apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #name: {{ .Values.app.backend.apiGateway.name }}-ingress
  name: {{ .Values.app.name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  #ingressClassName: ngingx
  rules:
    - host: {{ .Values.app.ingressDomain }}
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: {{ .Values.app.backend.apiGateway.name }}-service
              port: 
                number: {{ .Values.app.backend.apiGateway.port }}
                



