apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.backend.apiGateway.name }}-service
spec:
  type:  ClusterIP
  ports:
    - port: {{ .Values.app.backend.apiGateway.port }}
      protocol: TCP
  selector: 
    {{ toYaml .Values.app.backend.apiGateway.labels }}      

